/** @type {import('cz-git').UserConfig} */
module.exports = {
  types: [
    { value: "feat", name: "feat:     ✨ A new feature" },
    { value: "fix", name: "fix:      🐛 A bug fix" },
    { value: "docs", name: "docs:     📝 Documentation only changes" },
    { value: "style", name: "style:    💅 Code style changes" },
    { value: "refactor", name: "refactor: ♻️  Code refactoring" },
    { value: "perf", name: "perf:     ⚡ Performance improvement" },
    { value: "test", name: "test:     ✅ Adding or correcting tests" },
    { value: "build", name: "build:    🏗️  Build or dependency changes" },
    { value: "ci", name: "ci:        🤖 CI/CD related updates" },
    { value: "chore", name: "chore:    🔧 Maintenance / tooling" },
    { value: "revert", name: "revert:   ⏪ Revert previous commits" },
  ],
  scopes: [
    { name: "src" },
    { name: "scripts" },
    { name: "emoji-forge" },
    { name: "emoji-registry" },
    { name: "docs" },
    { name: "ci" },
    { name: "config" },
    { name: "release" },
  ],
  messages: {
    type: "Select the type of change that you’re committing:",
    scope: "Select a scope (optional):",
    subject: "Write a short, imperative description:\n",
    body: "Provide a longer description (optional):\n",
    breaking: "List any BREAKING CHANGES (optional):\n",
    footer: "List any issues closed by this change (optional):\n",
    confirmCommit: "Are you sure you want to proceed with the commit above?",
  },
  allowCustomScopes: true,
  allowBreakingChanges: ["feat", "fix"],
  skipQuestions: ["body", "footer"],
  subjectLimit: 100,
};
